version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8080:80"
    volumes:
      - ./src/laravel-app/public:/var/www/html/public
      - ./src/laravel-app/storage:/var/www/html/storage
    depends_on:
      - db
    command: /bin/bash -c "composer install && php artisan key:generate && php artisan migrate && php-fpm"
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - ./src/laravel-app/mysql-data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge